# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XFG-vtSwz6NIUU-UhhDoPxouW0v0_NoD
"""

def calculator():
    """A simple calculator that performs basic arithmetic operations."""

    while True:
        print("Welcome to the Simple Calculator!")
        print("Please enter the first number:")
        num1 = float(input())

        print("Please enter the second number:")
        num2 = float(input())

        print("Choose an operation:")
        print("1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        print("4. Division")
        print("5. Quit")

        choice = input("Enter your choice (1-5): ")

        if choice == '1':
            result = num1 + num2
            print(f"{num1} + {num2} = {result}")
        elif choice == '2':
            result = num1 - num2
            print(f"{num1} - {num2} = {result}")
        elif choice == '3':
            result = num1 * num2
            print(f"{num1} * {num2} = {result}")
        elif choice == '4':
            if num2 == 0:
                print("Error: Cannot divide by zero.")
            else:
                result = num1 / num2
                print(f"{num1} / {num2} = {result}")
        elif choice == '5':
            print("Exiting...")
            break
        else:
            print("Invalid choice. Please try again.")

        print("\nWould you like to perform another calculation? (y/n)")
        if input().lower() != 'y':
            break

if __name__ == "__main__":
    calculator()