# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eabNynzd-r4SXeJ7-XSWebRqbyDntPfe
"""

def add_task():
    """Adds a new task to the list of tasks.

    Prompts the user to enter the task description and appends it to the global `tasks` list.
    """

    print("Enter a new task:")
    task_description = input()

    global tasks
    tasks.append(task_description)

    print(f"Task '{task_description}' added successfully!")


def view_tasks():
    """Displays all the tasks in the list.

    Prints a numbered list of tasks, making it easier to identify and manage them.
    """

    print("Your tasks:")

    if not tasks:
        print("No tasks currently in the list.")
    else:
        for index, task in enumerate(tasks, 1):
            print(f"{index}. {task}")


def main():
    """The main function that controls the flow of the application.

    Provides a menu-driven interface for users to interact with the task list.
    """

    while True:
        print("\nTask Management Application")
        print("--------------------------")
        print("1. Add Task")
        print("2. View Tasks")
        print("3. Quit")
        print("--------------------------")

        choice = input("Enter your choice (1-3): ")

        if choice == "1":
            add_task()
        elif choice == "2":
            view_tasks()
        elif choice == "3":
            print("Exiting the application...")
            break
        else:
            print("Invalid choice. Please enter a number between 1 and 3.")


if __name__ == "__main__":
    main()